version: '3'
services:

  db:
    image: postgres
    volumes:
      - ./data/postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"

  redis:
    container_name: redis
    image: redis:3.2.0
    expose:
      - "6379"
    volumes:
      - ./data/redis-data:/data
    command: redis-server

  django:
    build: .
    command: sh runserver.sh
    links:
      - redis:redis
      - db:db
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - .:/opt/coronavirus_plot_web
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    links: 
      - redis:redis
    environment:
      - CELERY_BROKER_URL=redis://redis
    volumes:
      - .:/opt/coronavirus_plot_web
    command: celery worker -A coronavirus_plot_web -B -l info
    depends_on:
      - django
      - redis